Update developer README.md issue #1648
armadaproject/armada pull request #1654
Opened 2022-10-18 01:24 UTC by scoomthesnooper

Added: Note that only the personal-anonymous user can by default have jobs created by the anonymous user.

2022-10-18 13:40 UTC, kannon92 commented
Hello @scoomthesnooper!  Welcome to Armada.  Thank you for your first contribution.  

I assigned @Sharpz7 to take a look.

2022-10-18 19:59 UTC, suprjinx requested changes

2022-10-18 19:59 UTC, suprjinx commented on docs/dev/README.md
> +Note: Currently due to End-to-End test rules on the current localdev setup, only the personal-anonymous user can by default have jobs created by anonymous user when using no authentication.
This document isn't really describing the localdev setup -- so maybe this fact is not needed. I'd say move the change to docs/developer.md

2022-10-18 21:45 UTC, scoomthesnooper commented
I have changed it to developer.md i placed it at the bottom of the document as that is just after where it talks about authentication

2022-10-19 14:02 UTC, kannon92 commented on docs/dev/README.md
> +
nit: please remove the whitespace.

2022-10-19 15:40 UTC, Sharpz7 requested changes
Left a message about slightly re-wording what is written.

Also, if you can add "Closes #issue_id" to your PR message, then the issue will automatically close when the PR gets merged. See more here: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2023-02-01 15:22 UTC, closed without merging