Center aligned header
armadaproject/armada pull request #2176
Opened 2023-02-24 01:21 UTC by the-amazing-atharva

Fixes #2165 

#### Special notes for your reviewer:

-

2023-02-24 16:00 UTC, kannon92 submitted a review, later dismissed

2023-02-24 16:09 UTC, kannon92 commented
You have conflicts in the README.  Could you fix that? After that it is good to go.

2023-02-25 04:51 UTC, the-amazing-atharva commented
> You have conflicts in the README. Could you fix that? After that it is good to go.

Just resolved them
Is it proper now?

2023-02-25 13:25 UTC, kannon92 requested changes
Align center looks good but let’s please keep those badges

2023-02-25 13:25 UTC, kannon92 commented on README.md
> -[![CircleCI](https://circleci.com/gh/armadaproject/armada.svg?style=shield)](https://circleci.com/gh/armadaproject/armada)
Please add back these badges

2023-02-25 14:48 UTC, the-amazing-atharva commented
Sent a new PR, as I made an error while resolving (have not yet resolved a conflict b4)

2023-02-25 14:48 UTC, closed without merging