SQL Databases Interfaces
armadaproject/armada pull request #2624
Opened 2023-06-30 16:23 UTC by em-r

#### What type of PR is this?
Design Proposal.

#### What this PR does / why we need it:
This PR represents a proposal for defining database-agnostic interfaces that will assist in removing the tight coupling between Armada and the Postgres client `pgx`.

#### Which issue(s) this PR fixes:

Fixes #2121

#### Special notes for your reviewer:
This PR can be considered an in-progress PR, the proposed interfaces were verified against the existing Postgres implementation on `Lookout`, `LookoutV2`, and `Scheduler`. New changes might be introduced after completing the investigation of the remaining components (e.g. JobService)

2023-07-01 15:25 UTC, satyampsoni requested changes

2023-07-01 15:25 UTC, satyampsoni commented on docs/design/database_interfaces.md
> +Most of the components (Lookout, Scheduler, Scheduler Ingester) rely on [PostgresConfig](github.com/armadaproject/armada/internal/armada/configuration) to connect to external databases, we can avoid
The link produces an error 404. 
```suggestion
Most of the components (Lookout, Scheduler, Scheduler Ingester) rely on [PostgresConfig](https://github.com/armadaproject/armada/tree/master/internal/armada/configuration) to connect to external databases, we can avoid hardcoding the configuration of those components to use `PostgresConfig` but defining a generic `DatabaseConfig` interface that's when implemented will provide those components with the necessary details to connect to databases.
```

2023-07-01 15:35 UTC, em-r commented on docs/design/database_interfaces.md
> +Most of the components (Lookout, Scheduler, Scheduler Ingester) rely on [PostgresConfig](github.com/armadaproject/armada/internal/armada/configuration) to connect to external databases, we can avoid
fixed, thanks!

2023-07-03 19:32 UTC, suprjinx approved these changes

2023-07-04 11:39 UTC, kannon92 approved these changes
LGTM

2023-07-05 23:29 UTC, merged